export default {
	// ACTIONS
	ARTICLES_RECEIVE_DATA: 'ARTICLES_RECEIVE_DATA',
	ARTICLES_RECEIVE_DATA_ERROR: 'ARTICLES_RECEIVE_DATA_ERROR',
	ARTICLE_AWAIT_CREATION_RESPONSE: 'ARTICLE_AWAIT_CREATION_RESPONSE',
	ARTICLE_RECEIVE_CREATION_RESPONSE: 'ARTICLE_RECEIVE_CREATION_RESPONSE',
	ARTICLE_EDIT: 'ARTICLE_EDIT',
	ARTICLE_EDIT_FINISH: 'ARTICLE_EDIT_FINISH',
	ARTICLE_EDIT_SUBMIT: 'ARTICLE_EDIT_SUBMIT',

	// STATES
	ARTICLE_EDITING: 'ARTICLE_EDITING',
	ARTICLE_SUBMITTING: 'ARTICLE_SUBMITTING'
};
