/*
This file contains all would-be-magic-strings in the app.
*/

module.exports = {
	// MISC
	FIREBASE: 'https://brilliant-inferno-6675.firebaseio.com',

	// UI FEEDBACK ACTIONS
	DISPLAY_ERROR: 'DISPLAY_ERROR',
	DISPLAY_MESSAGE: 'DISPLAY_MESSAGE',
	DISMISS_FEEDBACK: 'DISMISS_FEEDBACK',

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: 'ATTEMPTING_LOGIN',
	LOGIN_USER: 'LOGIN_USER',
	LOGOUT: 'LOGOUT',

	// AUTH STATES
	LOGGED_IN: 'LOGGED_IN',
	ANONYMOUS: 'ANONYMOUS',
	AWAITING_AUTH_RESPONSE: 'AWAITING_AUTH_RESPONSE',

	// ARTICLE ACTIONS
	RECEIVE_ARTICLES_DATA: 'RECEIVE_ARTICLES_DATA',
	AWAIT_NEW_ARTICLE_RESPONSE: 'AWAIT_NEW_ARTICLE_RESPONSE',
	RECEIVE_NEW_ARTICLE_RESPONSE: 'RECEIVE_NEW_ARTICLE_RESPONSE',
	START_ARTICLE_EDIT: 'START_ARTICLE_EDIT',
	FINISH_ARTICLE_EDIT: 'FINISH_ARTICLE_EDIT',
	SUBMIT_ARTICLE_EDIT: 'SUBMIT_ARTICLE_EDIT',

	// ARTICLE STATES
	EDITING_ARTICLE: 'EDITING_ARTICLE',
	SUBMITTING_ARTICLE: 'SUBMITTING_ARTICLE'
};
